using System.Security.Cryptography;
using System.Text;

namespace Briefcase.SdkGenerator;

internal readonly record struct GenerationResult(
    string OutputDirectory,
    string ProjectPath,
    string AssemblyName,
    int TypeCount,
    bool SourcesChanged);

internal static class SourceSdkGenerator
{
    private const string GeneratorSchema = "9";
    private const ulong OutParameterFlag = 0x100;
    private const ulong ReturnParameterFlag = 0x400;
    private const ulong ReferenceParameterFlag = 0x08000000;
    private const ulong ConstParameterFlag = 0x2;
    private static readonly HashSet<string> Keywords = new(StringComparer.Ordinal)
    {
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch",
        "char", "checked", "class", "const", "continue", "decimal", "default",
        "delegate", "do", "double", "else", "enum", "event", "explicit",
        "extern", "false", "finally", "fixed", "float", "for", "foreach",
        "goto", "if", "implicit", "in", "int", "interface", "internal",
        "is", "lock", "long", "namespace", "new", "null", "object", "operator",
        "out", "override", "params", "private", "protected", "public", "readonly",
        "ref", "return", "sbyte", "sealed", "short", "sizeof", "stackalloc",
        "static", "string", "struct", "switch", "this", "throw", "true", "try",
        "typeof", "uint", "ulong", "unchecked", "unsafe", "ushort", "using",
        "virtual", "void", "volatile", "while"
    };

    public static GenerationResult Generate(string root, SdkSnapshot snapshot, string modSdkPath)
    {
        if (snapshot.Target is not ("Client" or "Server"))
            throw new InvalidDataException($"Unsupported target {snapshot.Target}.");
        if (string.IsNullOrWhiteSpace(snapshot.SdkAssemblyName))
            throw new InvalidDataException("The SDK assembly name is empty.");

        var buildId = $"{snapshot.GameBuild.PeTimestamp:X8}-{snapshot.GameBuild.ImageSize:X8}";
        var output = Path.Combine(root, "Sdk", "Generated", snapshot.Target, buildId);
        var projectPath = Path.Combine(output, snapshot.SdkAssemblyName + ".csproj");
        var completion = Path.Combine(output, ".complete");
        if (File.Exists(completion) && File.ReadAllText(completion) == GeneratorSchema)
            return new GenerationResult(
                output, projectPath, snapshot.SdkAssemblyName,
                snapshot.Types.Count(type => type.Kind is "Class" or "ScriptStruct" or "Enum"), false);

        Directory.CreateDirectory(output);
        var generatedDirectory = Path.Combine(output, "Generated");
        // Every schema describes the complete generated source set. Remove the
        // previous set before publishing a new one so renamed namespaces and
        // deleted types cannot survive as stale .cs files in the next build.
        var ready = Path.Combine(output, ".ready");
        if (File.Exists(ready)) File.Delete(ready);
        if (Directory.Exists(generatedDirectory))
            Directory.Delete(generatedDirectory, recursive: true);
        Directory.CreateDirectory(generatedDirectory);

        var types = snapshot.Types
            .Where(type => type.Kind is "Class" or "ScriptStruct" or "Enum" &&
                           type.Path.StartsWith("/Script/", StringComparison.Ordinal))
            .GroupBy(type => type.Path, StringComparer.Ordinal)
            .Select(group => group.First())
            .OrderBy(type => type.Path, StringComparer.Ordinal)
            .ToArray();
        var names = BuildTypeNames(types, snapshot.Target);

        foreach (var namespaceGroup in types.GroupBy(type => names[type.Path].Namespace)
                     .OrderBy(group => group.Key, StringComparer.Ordinal))
        {
            var source = new StringBuilder(256 * 1024);
            source.AppendLine("// <auto-generated />")
                  .AppendLine("#nullable enable")
                  .AppendLine("using System.Runtime.InteropServices;")
                  .AppendLine("using Briefcase.ModApi;")
                  .AppendLine("using Briefcase.ModApi.Interop;")
                  .Append("namespace ").Append(namespaceGroup.Key).AppendLine(";").AppendLine();
            foreach (var type in namespaceGroup.OrderBy(type => type.Path, StringComparer.Ordinal))
            {
                if (type.Kind == "ScriptStruct") WriteStruct(source, type, names);
                else if (type.Kind == "Enum") WriteEnum(source, type, names);
                else WriteType(source, type, names);
            }
            var fileName = Identifier(namespaceGroup.Key.Replace('.', '_')) + ".g.cs";
            File.WriteAllText(Path.Combine(generatedDirectory, fileName), source.ToString(),
                new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        }

        File.WriteAllText(projectPath, ProjectFile(snapshot.SdkAssemblyName, modSdkPath),
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        File.WriteAllText(Path.Combine(output, "snapshot.txt"),
            Path.Combine(root, "Sdk", "Metadata",
                $"DeceiveInc.{snapshot.Target}.{buildId}.json"));
        File.WriteAllText(completion, GeneratorSchema);
        return new GenerationResult(
            output, projectPath, snapshot.SdkAssemblyName, types.Length, true);
    }

    private static Dictionary<string, GeneratedTypeName> BuildTypeNames(
        IReadOnlyList<TypeSnapshot> types, string target)
    {
        var result = new Dictionary<string, GeneratedTypeName>(StringComparer.Ordinal);
        foreach (var namespaceGroup in types.GroupBy(type => NamespaceFor(type.Path, target)))
        {
            foreach (var nameGroup in namespaceGroup.GroupBy(
                         type => type.Kind switch
                         {
                             "ScriptStruct" => "F" + Identifier(type.Name).TrimStart('F'),
                             "Enum" => "E" + Identifier(type.Name).TrimStart('E'),
                             _ => Identifier(type.Name)
                         }, StringComparer.Ordinal))
            {
                var ordered = nameGroup.OrderBy(type => type.Path, StringComparer.Ordinal).ToArray();
                for (var index = 0; index < ordered.Length; index++)
                {
                    var name = nameGroup.Key;
                    if (ordered.Length > 1)
                        name += "_" + StableSuffix(ordered[index].Path);
                    result.Add(ordered[index].Path, new GeneratedTypeName(namespaceGroup.Key, name));
                }
            }
        }
        return result;
    }

    private static void WriteEnum(
        StringBuilder source, TypeSnapshot type, IReadOnlyDictionary<string, GeneratedTypeName> names)
    {
        var generatedName = names[type.Path];
        source.Append("[UnrealTypePath(").Append(Literal(type.Path)).AppendLine(")]")
              .Append("public enum ").Append(generatedName.Name).AppendLine(" : long")
              .AppendLine("{");
        var used = new HashSet<string>(StringComparer.Ordinal);
        foreach (var value in type.Values)
        {
            var separator = value.Name.LastIndexOf("::", StringComparison.Ordinal);
            var leaf = separator >= 0 ? value.Name[(separator + 2)..] : value.Name;
            source.Append("    ").Append(UniqueMember(leaf, "Value", used))
                  .Append(" = ").Append(value.Value).AppendLine(",");
        }
        source.AppendLine("}").AppendLine();
    }
    private static void WriteStruct(
        StringBuilder source, TypeSnapshot type, IReadOnlyDictionary<string, GeneratedTypeName> names)
    {
        if (type.Size <= 0 || type.Size > 65_535) return;
        var generatedName = names[type.Path];
        source.Append("[StructLayout(LayoutKind.Explicit, Size = ").Append(type.Size).AppendLine(")]" )
              .Append("public partial struct ").Append(generatedName.Name)
              .AppendLine(" : IUnrealStructValue")
              .AppendLine("{")
              .Append("    public const string UnrealPath = ").Append(Literal(type.Path)).AppendLine(";")
              .Append("    public const int NativeSize = ").Append(type.Size).AppendLine(";")
              .AppendLine("    readonly int IUnrealStructValue.Size => NativeSize;")
              .AppendLine("    readonly void IUnrealStructValue.WriteTo(Span<byte> destination)")
              .AppendLine("    {")
              .AppendLine("        if (destination.Length != NativeSize) throw new ArgumentException(\"Native struct size mismatch.\", nameof(destination));")
              .AppendLine("        var value = this;")
              .AppendLine("        MemoryMarshal.Write(destination, in value);")
              .AppendLine("    }");
        WriteReflectionAndMetadata(source, type);

        var used = new HashSet<string>(StringComparer.Ordinal)
            { "UnrealPath", "NativeSize", generatedName.Name };
        foreach (var property in type.Properties.OrderBy(property => property.Offset))
        {
            var managedType = ManagedType(property, names);
            if (managedType is null || property.ArrayDimension != 1 || property.Offset < 0 ||
                property.ElementSize <= 0 || property.Offset > type.Size - property.ElementSize)
                continue;
            var member = UniqueMember(property.Name, "Field", used);
            source.Append("    [FieldOffset(").Append(property.Offset).AppendLine(")]" )
                  .Append("    public ").Append(managedType).Append(' ').Append(member).AppendLine(";");
        }
        source.AppendLine("}").AppendLine();
    }

    private static void WriteType(
        StringBuilder source, TypeSnapshot type, IReadOnlyDictionary<string, GeneratedTypeName> names)
    {
        var generatedName = names[type.Path];
        GeneratedTypeName parent = default;
        var hasGeneratedBase = type.SuperPath is not null && names.TryGetValue(type.SuperPath, out parent);
        var baseType = hasGeneratedBase
            ? $"global::{parent.Namespace}.{parent.Name}"
            : "UnrealObject";
        source.Append("public partial class ").Append(generatedName.Name)
              .Append(" : ").Append(baseType).Append(", IUnrealObject<")
              .Append(generatedName.Name).AppendLine(">")
              .AppendLine("{")
              .Append("    protected ").Append(generatedName.Name)
              .AppendLine("(UnrealApi api, UnrealObjectHandle handle) : base(api, handle) { }")
              .Append("    public ").Append(hasGeneratedBase ? "new " : "")
              .Append("static ").Append(generatedName.Name)
              .AppendLine(" FromObject(UnrealApi api, UnrealObjectHandle handle) => new(api, handle);")
              .Append("    public const string UnrealPath = ").Append(Literal(type.Path)).AppendLine(";")
              .Append("    public static UnrealClass<").Append(generatedName.Name)
              .AppendLine("> StaticClass { get; } = new(UnrealPath);")
              .AppendLine();
        WriteReflectionAndMetadata(source, type);

        var usedMembers = new HashSet<string>(StringComparer.Ordinal)
        { "Handle", "Name", "Path", "ClassHandle", "StaticClass", "Properties",
          "Metadata", "Reflection",
          "Functions", "UnrealPath", "FromObject", "Read", "ReadString", "ReadText",
          "InvokeText", "IsA" };
        usedMembers.Add(generatedName.Name);
        var propertyCandidates = type.Properties
            .Select(property => (Property: property, Type: ManagedType(
                property, names, allowStringProperty: true)))
            .Where(item => item.Type is not null && item.Property.ArrayDimension == 1)
            .OrderBy(item => item.Property.Name, StringComparer.Ordinal)
            .ToArray();
        var supportedProperties = new List<(PropertySnapshot Property, string Type, string Member)>();
        foreach (var item in propertyCandidates)
        {
            var member = UniqueMember(item.Property.Name, "Property", usedMembers);
            supportedProperties.Add((item.Property, item.Type!, member));
            source.Append("    public ").Append(item.Type).Append(' ').Append(member)
                  .Append(item.Type == "string" ? " => ReadString(Properties." :
                          item.Type == "UnrealText" ? " => ReadText(Properties." : " => Read(Properties.")
                  .Append(member).AppendLine(");");
        }
        if (supportedProperties.Count > 0) source.AppendLine();

        var supportedFunctions = type.Functions
            .Where(function => IsCallableFunction(function, names))
            .OrderBy(function => function.Name, StringComparer.Ordinal)
            .Select(function => (Function: function, Member: UniqueMember(function.Name, "Method", usedMembers)))
            .ToArray();
        foreach (var item in supportedFunctions)
        {
            var parameters = item.Function.Parameters.OrderBy(parameter => parameter.Offset).ToArray();
            var inputs = parameters.Where(parameter => !IsReturnParameter(parameter)).ToArray();
            var returnParameter = parameters.SingleOrDefault(IsReturnParameter);
            var returnType = returnParameter is null
                ? null
                : ManagedType(returnParameter, names, allowTextProperty: true);
            source.Append("    public ").Append(returnType ?? "void").Append(' ')
                  .Append(item.Member).Append('(');
            for (var index = 0; index < inputs.Length; index++)
            {
                if (index > 0) source.Append(", ");
                source.Append(ManagedType(inputs[index], names, allowInputContainers: true)).Append(' ')
                      .Append(ParameterIdentifier(inputs[index].Name));
            }
            source.Append(") => ");
            if (returnType is null)
                source.Append("InvokeVoid(Functions.");
            else if (returnType == "UnrealText")
                source.Append("InvokeText(Functions.");
            else
                source.Append("Invoke<").Append(returnType).Append(">(Functions.");
            source.Append(item.Member);
            foreach (var parameter in inputs)
                source.Append(", ").Append(ParameterIdentifier(parameter.Name));
            source.AppendLine(");");
        }
        if (supportedFunctions.Length > 0) source.AppendLine();

        source.AppendLine("    public static class Properties").AppendLine("    {");
        foreach (var item in supportedProperties)
        {
            source.Append("        public static UnrealProperty<").Append(item.Type).Append("> ")
                  .Append(item.Member).Append(" { get; } = new(UnrealPath, ")
                  .Append(Literal(item.Property.Name)).Append(", ").Append(item.Property.Offset)
                  .Append(", ").Append(item.Property.ElementSize).AppendLine(");");
        }
        source.AppendLine("    }").AppendLine();

        source.AppendLine("    public static class Functions").AppendLine("    {");
        foreach (var item in supportedFunctions)
        {
            var parameters = item.Function.Parameters.OrderBy(parameter => parameter.Offset).ToArray();
            source.Append("        public static UnrealFunction ").Append(item.Member)
                  .Append(" { get; } = new(UnrealPath, ").Append(Literal(item.Function.Name))
                  .Append(", ").Append(item.Function.ParameterSize).Append(", [");
            for (var index = 0; index < parameters.Length; index++)
            {
                if (index > 0) source.Append(", ");
                var parameter = parameters[index];
                source.Append("new UnrealParameter(").Append(Literal(parameter.Name))
                      .Append(", typeof(").Append(ManagedType(
                          parameter, names,
                          allowInputContainers: !IsReturnParameter(parameter),
                          allowTextProperty: true)).Append("), ")
                      .Append(parameter.Offset).Append(", ").Append(parameter.ElementSize);
                if (IsReturnParameter(parameter)) source.Append(", true");
                source.Append(')');
            }
            var returnParameter = parameters.SingleOrDefault(IsReturnParameter);
            if (returnParameter is null)
            {
                source.AppendLine("]);");
            }
            else
            {
                var returnType = ManagedType(
                    returnParameter, names, allowTextProperty: true)!;
                source.Append("], typeof(").Append(returnType).Append("))")
                      .Append(" { ReturnParameter = new UnrealParameter(")
                      .Append(Literal(returnParameter.Name)).Append(", typeof(")
                      .Append(returnType).Append("), ").Append(returnParameter.Offset)
                      .Append(", ").Append(returnParameter.ElementSize)
                      .AppendLine(", true) };");
            }
        }
        source.AppendLine("    }").AppendLine("}").AppendLine();
    }

    private static void WriteReflectionAndMetadata(StringBuilder source, TypeSnapshot type)
    {
        var reflectedKind = type.Kind == "Class"
            ? "UnrealReflectedTypeKind.Class"
            : "UnrealReflectedTypeKind.Struct";
        source.Append("    public static UnrealReflectedType Reflection { get; } = new(")
              .Append(Literal(type.Path)).Append(", ")
              .Append(Literal(type.Name)).Append(", ")
              .Append(reflectedKind).Append(", ")
              .Append(type.SuperPath is null ? "null" : Literal(type.SuperPath)).Append(", ")
              .Append(type.Size).AppendLine(");")
              .AppendLine("    public static class Metadata")
              .AppendLine("    {")
              .AppendLine("        public static class Properties")
              .AppendLine("        {");

        var propertyNames = new HashSet<string>(StringComparer.Ordinal) { "Properties" };
        foreach (var property in type.Properties
                     .OrderBy(property => property.Name, StringComparer.Ordinal)
                     .ThenBy(property => property.Offset))
        {
            var member = UniqueMember(property.Name, "Property", propertyNames);
            source.Append("            public static UnrealReflectedProperty ")
                  .Append(member).Append(" { get; } = new(")
                  .Append(Literal(property.Name)).Append(", ")
                  .Append(property.Offset).Append(", ")
                  .Append(property.ElementSize).Append(", ")
                  .Append(property.ArrayDimension).Append(", ")
                  .Append(property.Flags).Append("UL, ")
                  .Append(TypeMetadataExpression(property.EffectiveType)).AppendLine(");");
        }

        source.AppendLine("        }")
              .AppendLine("        public static class Functions")
              .AppendLine("        {");
        var functionNames = new HashSet<string>(StringComparer.Ordinal) { "Functions" };
        foreach (var function in type.Functions.OrderBy(
                     function => function.Name, StringComparer.Ordinal))
        {
            var member = UniqueMember(function.Name, "Function", functionNames);
            source.Append("            public static UnrealReflectedFunction ")
                  .Append(member).Append(" { get; } = new(")
                  .Append(Literal(function.Name)).Append(", ")
                  .Append(function.Flags).Append("U, ")
                  .Append(function.ParameterSize).Append(", ")
                  .Append(function.ParameterCount).Append(", [");
            for (var index = 0; index < function.Parameters.Count; index++)
            {
                if (index != 0) source.Append(", ");
                var parameter = function.Parameters[index];
                source.Append("new UnrealReflectedParameter(")
                      .Append(Literal(parameter.Name)).Append(", ")
                      .Append(parameter.Offset).Append(", ")
                      .Append(parameter.ElementSize).Append(", ")
                      .Append(parameter.ArrayDimension).Append(", ")
                      .Append(parameter.Flags).Append("UL, ")
                      .Append(TypeMetadataExpression(parameter.EffectiveType)).Append(')');
            }
            source.AppendLine("]);");
        }
        source.AppendLine("        }")
              .AppendLine("    }")
              .AppendLine();
    }

    private static string TypeMetadataExpression(UnrealTypeSnapshot type)
    {
        var result = new StringBuilder("new UnrealTypeMetadata(UnrealTypeKind.")
            .Append(MetadataKind(type.UnrealType, type.ReferencedTypePath))
            .Append(", ").Append(Literal(type.UnrealType))
            .Append(", ").Append(type.ElementSize)
            .Append(", ").Append(type.ReferencedTypePath is null
                ? "null"
                : Literal(type.ReferencedTypePath))
            .Append(", ").Append(type.InnerType is null
                ? "null"
                : TypeMetadataExpression(type.InnerType))
            .Append(", ").Append(type.KeyType is null
                ? "null"
                : TypeMetadataExpression(type.KeyType))
            .Append(", ").Append(type.ValueType is null
                ? "null"
                : TypeMetadataExpression(type.ValueType))
            .Append(", ").Append(type.UnderlyingType is null
                ? "null"
                : TypeMetadataExpression(type.UnderlyingType))
            .Append(", ");
        if (type.BooleanLayout is { } boolean)
        {
            result.Append("new UnrealBooleanLayout(")
                  .Append(boolean.FieldSize).Append(", ")
                  .Append(boolean.ByteOffset).Append(", ")
                  .Append(boolean.ByteMask).Append(", ")
                  .Append(boolean.FieldMask).Append(')');
        }
        else
        {
            result.Append("null");
        }
        return result.Append(')').ToString();
    }

    private static string MetadataKind(string unrealType, string? referencedTypePath) =>
        unrealType switch
        {
            "BoolProperty" => "Boolean",
            "Int8Property" => "Int8",
            "ByteProperty" => referencedTypePath is null
                ? "UInt8"
                : "Enum",
            "Int16Property" => "Int16",
            "UInt16Property" => "UInt16",
            "IntProperty" => "Int32",
            "UInt32Property" => "UInt32",
            "Int64Property" => "Int64",
            "UInt64Property" => "UInt64",
            "FloatProperty" => "Float",
            "DoubleProperty" => "Double",
            "EnumProperty" => "Enum",
            "NameProperty" => "Name",
            "StrProperty" => "String",
            "TextProperty" => "Text",
            "ObjectProperty" => "Object",
            "ClassProperty" => "Class",
            "InterfaceProperty" => "Interface",
            "WeakObjectProperty" => "WeakObject",
            "LazyObjectProperty" => "LazyObject",
            "SoftObjectProperty" => "SoftObject",
            "SoftClassProperty" => "SoftClass",
            "StructProperty" => "Struct",
            "ArrayProperty" => "Array",
            "SetProperty" => "Set",
            "MapProperty" => "Map",
            "DelegateProperty" => "Delegate",
            "MulticastDelegateProperty" or "MulticastInlineDelegateProperty" or
                "MulticastSparseDelegateProperty" => "MulticastDelegate",
            "FieldPathProperty" => "FieldPath",
            _ => "Unknown"
        };
    private static bool IsCallableFunction(
        FunctionSnapshot function, IReadOnlyDictionary<string, GeneratedTypeName> names)
    {
        var returnCount = function.Parameters.Count(IsReturnParameter);
        if (returnCount > 1) return false;
        foreach (var parameter in function.Parameters)
        {
            var isReturn = IsReturnParameter(parameter);
            // A single ordinary return value is supported. Additional out/ref
            // parameters still need a generated result type and are therefore
            // deliberately excluded from this schema.
            var managedType = ManagedType(
                parameter, names, allowInputContainers: !isReturn,
                allowTextProperty: true);
            // UE represents `const FStruct&` as ConstParm | OutParm |
            // ReferenceParm even though ProcessEvent stores the value inline.
            var isConstReference =
                (parameter.Flags & (ConstParameterFlag | ReferenceParameterFlag)) ==
                (ConstParameterFlag | ReferenceParameterFlag);
            if (!isReturn && (parameter.Flags & OutParameterFlag) != 0 &&
                !isConstReference)
                return false;
            // A native const-reference struct is represented inline in the
            // ProcessEvent parameter buffer. Its generated C# method accepts a
            // blittable value; patch methods may request `ref` when they need
            // the bridge to copy a changed value back before the original call.
            if (!isReturn && (parameter.Flags & ReferenceParameterFlag) != 0 &&
                managedType is not ("string" or "UnrealText" or "byte[]") &&
                parameter.EffectiveType.UnrealType != "StructProperty")
                return false;
            if (managedType is null ||
                parameter.ArrayDimension != 1 ||
                !CanUseExactParameterName(parameter.Name))
                return false;
        }
        return true;
    }

    private static bool IsReturnParameter(PropertySnapshot parameter) =>
        (parameter.Flags & ReturnParameterFlag) != 0;

    private static string? ManagedType(
        PropertySnapshot property,
        IReadOnlyDictionary<string, GeneratedTypeName> names,
        bool allowInputContainers = false,
        bool allowStringProperty = false,
        bool allowTextProperty = false)
    {
        var typeShape = property.EffectiveType;
        if (typeShape.UnrealType == "StructProperty" &&
            typeShape.ReferencedTypePath is { } path && names.TryGetValue(path, out var type))
            return $"global::{type.Namespace}.{type.Name}";
        return typeShape.UnrealType switch
        {
            "StrProperty" when allowInputContainers || allowStringProperty => "string",
            "TextProperty" when allowInputContainers || allowStringProperty || allowTextProperty =>
                "UnrealText",
            "NameProperty" => "UnrealName",
            "ArrayProperty" when allowInputContainers &&
                                 typeShape.InnerType?.UnrealType == "ByteProperty" => "byte[]",
            "IntProperty" => "int",
            "Int8Property" => "sbyte",
            "Int16Property" => "short",
            "ByteProperty" => "byte",
            "UInt16Property" => "ushort",
            "UInt32Property" => "uint",
            "Int64Property" => "long",
            "UInt64Property" => "ulong",
            "FloatProperty" => "float",
            "DoubleProperty" => "double",
            "BoolProperty" => "bool",
            "ObjectProperty" or "ClassProperty" => "UnrealObjectReference",
            "EnumProperty" => property.ElementSize switch
            {
                1 => "byte", 2 => "ushort", 4 => "uint", 8 => "ulong", _ => null
            },
            _ => null
        };
    }
    private static string NamespaceFor(string path, string target)
    {
        var moduleEnd = path.IndexOf('.', "/Script/".Length);
        var module = moduleEnd > 0 ? path["/Script/".Length..moduleEnd] : "Unknown";
        // Client and server SDKs are separate assemblies, but their C# API uses
        // identical namespaces. Shared mod source can consequently compile
        // against either target without conditional using directives.
        return string.Equals(module, "DeceiveInc", StringComparison.Ordinal)
            ? "Briefcase.DeceiveInc"
            : $"Briefcase.Unreal.{Identifier(module)}";
    }

    private static string UniqueMember(string unrealName, string suffix, HashSet<string> used)
    {
        var candidate = Identifier(unrealName);
        if (used.Add(candidate)) return EscapeKeyword(candidate);
        candidate += "_" + suffix;
        var number = 2;
        while (!used.Add(candidate)) candidate = Identifier(unrealName) + "_" + suffix + number++;
        return EscapeKeyword(candidate);
    }

    private static bool CanUseExactParameterName(string value)
    {
        if (string.IsNullOrEmpty(value)) return false;
        if (!(char.IsLetter(value[0]) || value[0] == '_')) return false;
        return value.All(character => char.IsLetterOrDigit(character) || character == '_');
    }

    private static string ParameterIdentifier(string value) =>
        EscapeKeyword(Identifier(value));

    private static string Identifier(string value)
    {
        if (string.IsNullOrEmpty(value)) return "Unnamed";
        var result = new StringBuilder(value.Length + 1);
        foreach (var character in value)
            result.Append(char.IsLetterOrDigit(character) || character == '_' ? character : '_');
        if (result.Length == 0) result.Append("Unnamed");
        if (char.IsDigit(result[0])) result.Insert(0, '_');
        return result.ToString();
    }

    private static string EscapeKeyword(string value) => Keywords.Contains(value) ? "@" + value : value;

    private static string StableSuffix(string value) =>
        Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(value)))[..8];

    private static string Literal(string value)
    {
        var result = new StringBuilder(value.Length + 2).Append('"');
        foreach (var character in value)
        {
            result.Append(character switch
            {
                '"' => "\\\"",
                '\\' => "\\\\",
                '\r' => "\\r",
                '\n' => "\\n",
                '\t' => "\\t",
                _ => character.ToString()
            });
        }
        return result.Append('"').ToString();
    }

    private static string ProjectFile(string assemblyName, string modSdkPath) =>
        $"""
        <Project Sdk="Microsoft.NET.Sdk">
          <PropertyGroup>
            <TargetFramework>net10.0</TargetFramework>
            <AssemblyName>{Xml(assemblyName)}</AssemblyName>
            <ImplicitUsings>enable</ImplicitUsings>
            <Nullable>enable</Nullable>
            <IsAotCompatible>true</IsAotCompatible>
            <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
            <!-- Unreal derived classes intentionally expose their own static
                 metadata and can redeclare reflected member names. -->
            <NoWarn>$(NoWarn);CS0108;CS0109</NoWarn>
          </PropertyGroup>
          <ItemGroup>
            <Reference Include="Briefcase.ModApi">
              <HintPath>{Xml(modSdkPath)}</HintPath>
              <Private>false</Private>
            </Reference>
          </ItemGroup>
        </Project>
        """;

    private static string Xml(string value) => value
        .Replace("&", "&amp;", StringComparison.Ordinal)
        .Replace("<", "&lt;", StringComparison.Ordinal)
        .Replace(">", "&gt;", StringComparison.Ordinal)
        .Replace("\"", "&quot;", StringComparison.Ordinal);

    private readonly record struct GeneratedTypeName(string Namespace, string Name);
}
