<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <AssemblyName>Briefcase.AvaloniaUi</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Briefcase.ManagedHost\Briefcase.ManagedHost.csproj" />
    <ProjectReference Include="..\Briefcase.ClientModApi\Briefcase.ClientModApi.csproj" />
    <ProjectReference Include="..\Briefcase.Rendering\Briefcase.Rendering.csproj" />
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.HarfBuzz" Version="12.1.2" />
    <PackageReference Include="Avalonia.Skia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Win32" Version="12.1.2" />
  </ItemGroup>
</Project>
